---

- hosts: rpi4
  become: true
  vars:
    tailscale_ip: "{{ ansible_facts.tailscale0.ipv4.address }}"
    local_ip: "{{ ansible_facts.default_ipv4.address }}"
  roles:
    - role: secured_rpi
      vars:
        secured_user: "{{ ansible_user }}"
    - role: docker
      tags: [ docker ]
      vars:
        docker_root: "{{ ssd_mount }}/docker"
        docker_users: ["{{ ansible_user }}"]
    - role: openldap
      tags: [ openldap ]
    - role: sssd
      tags: [ sssd ]
    - role: authelia
      tags: [ authelia ]
    - role: traefik
      tags: [ traefik ]
    - role: pihole
      tags: [ pihole ]
    - role: certbot
      tags: [ certbot ]
    - role: nginx
      tags: [ nginx ]
    - role: tailscale
      tags: [ tailscale ]
    - role: homepage
      tags: [ homepage ]
      