---

- hosts: rpi4
  become: true
  roles:
    - role: secured_rpi
      vars:
        secured_user: "{{ ansible_user }}"
    - role: docker
      tags: [ docker ]
      vars:
        docker_root: "{{ ssd_mount }}/docker"
        docker_users: ["{{ ansible_user }}"]
    - role: authelia
      tags: [ authelia ]
    - role: traefik
      tags: [ traefik ]
    - role: pihole
      tags: [ pihole ]
      