---

homelab:
  # host details (like IP address) stored in SSH config
  hosts:
    rpi4:
      ansible_user: "{{ rpi4.ansible_user }}"
      ansible_become_pass: "{{ lookup('env', 'rpi4_root_password') }}"
