- name: Install sssd packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - sssd
    - sssd-ldap
    - libnss-sss
    - libpam-sss 

- name: Configure sssd
  ansible.builtin.template:
    src: templates/sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: 0600
    backup: yes
    owner: root
    group: root
  notify:
    - restart sssd

- name: Enable sssd service
  service:
    name: sssd
    enabled: true

- name: Enable automatic home directory creation
  ansible.builtin.copy:
    dest: /usr/share/pam-configs/sssd_mkhomedir
    content: |
      Name: Create home directory on login
      Default: yes
      Priority: 900
      Session-Type: Additional
      Session:
        required        pam_mkhomedir.so umask=0077 skel=/etc/skel
  notify:
    - update pam auth