---

- name: Create Traefik directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ traefik_mount_dir }}"
    - "{{ traefik_mount_dir }}/letsencrypt"
    - "{{ traefik_mount_dir }}/logs"

- name: Get Authelia container info
  docker_container_info:
    name: authelia
  register: authelia_container_info

- name: Get Authelia container IP
  ansible.builtin.set_fact:
    authelia_container_ip: '{{ authelia_container_info.container.NetworkSettings.Networks["homelab"].IPAddress }}'

- name: Deploy Traefik Docker container
  community.docker.docker_container:
    name: traefik
    image: traefik:latest
    restart_policy: unless-stopped
    state: started
    security_opts:
      - no-new-privileges:true
    networks:
      - name: homelab
    env:
      TZ: '{{ tz }}'
      CF_DNS_API_TOKEN: "{{ cloudflare_dns_api_token }}"
    command:
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
      - "--api=true"
      - "--api.dashboard=true"
      # Logging
      - "--log.level=INFO"
      - "--log.filePath=/logs/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filepath=/logs/access.log"
      # Docker provider
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.watch=true"
      # HTTP endpoint
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.forwardedHeaders.insecure=false"
      - "--entrypoints.web.proxyProtocol.insecure=false"
      - "--entrypoints.web.forwardedHeaders.trustedIPs={{ authelia_container_ip }}"
      - "--entrypoints.web.proxyProtocol.trustedIPs={{ authelia_container_ip }}"
      # HTTPS endpoint
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.asDefault=true"
      - "--entrypoints.websecure.forwardedHeaders.insecure=false"
      - "--entrypoints.websecure.proxyProtocol.insecure=false"
      - "--entrypoints.websecure.forwardedHeaders.trustedIPs={{ authelia_container_ip }}"
      - "--entrypoints.websecure.proxyProtocol.trustedIPs={{ authelia_container_ip }}"
      # Let's Encrypt config
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.email=acme@ganczarek.info"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '{{ traefik_mount_dir }}/letsencrypt:/letsencrypt'
      - '{{ traefik_mount_dir }}/logs:/logs'
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik-dashboard.rule: "Host(`traefik.{{ domain }}`) && (Path(`/`) || PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      traefik.http.routers.traefik-dashboard.service: "api@internal"
      traefik.http.routers.traefik-dashboard.tls: "true"
      traefik.http.routers.traefik-dashboard.tls.certresolver: "letsencrypt"
      traefik.http.routers.traefik-dashboard.middlewares: "authelia,traefik-dashboard-redirect"
      traefik.http.middlewares.traefik-dashboard-redirect.redirectregex.regex: '^(https:\/\/(\[[\w:.]+\]|[\w\._-]+)(:\d+)?)\/$'
      traefik.http.middlewares.traefik-dashboard-redirect.redirectregex.replacement: "${1}/dashboard/"
      traefik.http.middlewares.traefik-dashboard-redirect.redirectregex.permanent: "true"
      homepage.group: Networking
      homepage.name: Traefik
      homepage.href: https://traefik.{{ domain }}/
      homepage.icon: sh-traefik